### ISSUE TITLE
Spelling mistake here

### ISSUE THREAD

**Issue by KramKroc** [PacktPublishing/Learn-Go-in-3-Hours#1]
https://github.com/PacktPublishing/Learn-Go-in-3-Hours/blob/e9944c38e41a06a83ee51c147fb063c2a04e1710/Section3/functions/function7.go#L19

**Comment by KramKroc** [comment]
Should be divAndRemainder(-1, 20)

**Comment by jonbodner** [comment]
Fixed. Thanks for finding the error. I hope you have enjoyed the course!
